USE DB

DECLARE @X INT = 1

WHILE @X <= 30000
BEGIN
	INSERT PRODUTO VALUES (NEWID(), @X)
	
	SET @X += 1
END

SELECT * 
FROM PRODUTO

SELECT * 
FROM SYS.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('PRODUTO'), DEFAULT, DEFAULT, 'DETAILED')

UPDATE PRODUTO 
SET PRECO_PRODUTO = RAND() * 10000

UPDATE PRODUTO
SET NOME_PRODUTO = NOME_PRODUTO+'***'

SELECT * 
FROM SYS.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('PRODUTO'), DEFAULT, DEFAULT, 'DETAILED')

ALTER TABLE PRODUTO REBUILD

SELECT * 
FROM SYS.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('PRODUTO'), DEFAULT, DEFAULT, 'DETAILED')

DBCC SHOWCONTIG('PRODUTO')

SELECT * 
FROM SYS.dm_db_index_operational_stats(DB_ID(), OBJECT_ID('PRODUTO'), DEFAULT, DEFAULT)

EXEC SP_HELPINDEX 'PRODUTO'

ALTER TABLE PRODUTO
ADD PRIMARY KEY (COD_PRODUTO)

EXEC SP_HELPINDEX 'PRODUTO'

SELECT * 
FROM SYS.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('PRODUTO'), DEFAULT, DEFAULT, 'DETAILED')

ALTER INDEX PK__PRODUTO__AAF2697D7243347D 
ON PRODUTO 
REBUILD

SELECT * 
FROM SYS.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('PRODUTO'), DEFAULT, DEFAULT, 'DETAILED')

--DROP INDEX PRODUTO.PK__PRODUTO__AAF2697D7243347D 

ALTER TABLE PRODUTO
DROP CONSTRAINT PK__PRODUTO__AAF2697D7243347D

EXEC SP_HELPINDEX 'PRODUTO'

SELECT * 
FROM SYS.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('PRODUTO'), DEFAULT, DEFAULT, 'DETAILED')

CREATE CLUSTERED INDEX IDX_PRODUTO 
ON PRODUTO(COD_PRODUTO DESC)

CREATE CLUSTERED INDEX IDX_PRODUTO 
ON PRODUTO(COD_PRODUTO)
WITH DROP_EXISTING

EXEC SP_HELPINDEX 'PRODUTO'

DROP INDEX PRODUTO.IDX_PRODUTO

CREATE CLUSTERED INDEX IDX_PRODUTO 
ON PRODUTO(COD_PRODUTO)
WITH 
(
	FILLFACTOR = 100, 
	PAD_INDEX = ON
)

SELECT * 
FROM SYS.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('PRODUTO'), DEFAULT, DEFAULT, 'DETAILED')

ALTER INDEX IDX_PRODUTO ON PRODUTO REBUILD

SELECT * 
FROM SYS.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('PRODUTO'), DEFAULT, DEFAULT, 'DETAILED')

