USE master

IF EXISTS (SELECT * FROM SYS.databases WHERE name = 'DB')
BEGIN
	ALTER DATABASE DB
	SET SINGLE_USER
	WITH ROLLBACK IMMEDIATE

	DROP DATABASE DB
END

CREATE DATABASE DB
GO

USE DB

CREATE TABLE PRODUTO
(
	COD_PRODUTO INT IDENTITY, 
	NOME_PRODUTO VARCHAR(50),
	PRECO_PRODUTO DEC(9, 2)
)

DECLARE @X INT = 1

WHILE @X <= 30000
BEGIN
	INSERT PRODUTO 
	VALUES (NEWID(), RAND() * 100)
	
	SET @X += 1
END

SELECT * 
FROM PRODUTO

SELECT * 
FROM PRODUTO
WHERE NOME_PRODUTO = 'FAFDADFSDFD'

SELECT NOME_PRODUTO 
FROM PRODUTO

SELECT NOME_PRODUTO
FROM PRODUTO
WHERE NOME_PRODUTO = 'FAFDADFSDFD'

CREATE NONCLUSTERED INDEX IDX_PRODUTO_NOME_PRODUTO
ON PRODUTO (NOME_PRODUTO)

SELECT * 
FROM PRODUTO

SELECT * 
FROM PRODUTO
WHERE NOME_PRODUTO = 'FAFDADFSDFD'

SELECT NOME_PRODUTO 
FROM PRODUTO

SELECT NOME_PRODUTO
FROM PRODUTO
WHERE NOME_PRODUTO = 'FAFDADFSDFD'

SELECT * 
FROM SYS.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('PRODUTO'), DEFAULT, DEFAULT, 'DETAILED')

EXEC sp_spaceused 'PRODUTO'

CREATE NONCLUSTERED INDEX IDX_PRODUTO_NOME_PRODUTO
ON PRODUTO (NOME_PRODUTO, COD_PRODUTO, PRECO_PRODUTO)
WITH DROP_EXISTING

EXEC sp_spaceused 'PRODUTO'

SELECT * 
FROM PRODUTO

SELECT * 
FROM PRODUTO
WHERE NOME_PRODUTO = 'FAFDADFSDFD'

SELECT NOME_PRODUTO 
FROM PRODUTO

SELECT NOME_PRODUTO
FROM PRODUTO
WHERE NOME_PRODUTO = 'FAFDADFSDFD'

CREATE NONCLUSTERED INDEX IDX_PRODUTO_NOME_PRODUTO
ON PRODUTO (NOME_PRODUTO)
INCLUDE(COD_PRODUTO, PRECO_PRODUTO)
WITH DROP_EXISTING

EXEC sp_spaceused 'PRODUTO'

SELECT * 
FROM PRODUTO

SELECT * 
FROM PRODUTO
WHERE NOME_PRODUTO = 'FAFDADFSDFD'

SELECT NOME_PRODUTO 
FROM PRODUTO

SELECT NOME_PRODUTO
FROM PRODUTO
WHERE NOME_PRODUTO = 'FAFDADFSDFD'

EXEC SP_HELPINDEX 'PRODUTO'

ALTER INDEX IDX_PRODUTO_NOME_PRODUTO 
ON PRODUTO 
DISABLE

SELECT NOME_PRODUTO
FROM PRODUTO
WHERE NOME_PRODUTO = 'FAFDADFSDFD'

ALTER TABLE PRODUTO 
ADD ATIVO_PRODUTO BIT

UPDATE PRODUTO 
SET ATIVO_PRODUTO = 1

ALTER INDEX IDX_PRODUTO_NOME_PRODUTO 
ON PRODUTO 
REBUILD

SELECT NOME_PRODUTO
FROM PRODUTO
WHERE NOME_PRODUTO = 'FAFDADFSDFD'

UPDATE PRODUTO
SET ATIVO_PRODUTO = 0 
WHERE COD_PRODUTO % 3 IN (1, 2)

CREATE NONCLUSTERED INDEX IDX_PRODUTO_NOME_PRODUTO
ON PRODUTO (NOME_PRODUTO)
INCLUDE(COD_PRODUTO, PRECO_PRODUTO)
WHERE ATIVO_PRODUTO = 1
WITH DROP_EXISTING

EXEC sp_spaceused 'PRODUTO'

SELECT NOME_PRODUTO 
FROM PRODUTO

SELECT NOME_PRODUTO 
FROM PRODUTO
WHERE ATIVO_PRODUTO = 1

SELECT *
FROM PRODUTO
WHERE ATIVO_PRODUTO = 1

CREATE NONCLUSTERED INDEX IDX_PRODUTO_NOME_PRODUTO
ON PRODUTO (NOME_PRODUTO)
INCLUDE(COD_PRODUTO, PRECO_PRODUTO, ATIVO_PRODUTO)
WHERE ATIVO_PRODUTO = 1
WITH DROP_EXISTING

EXEC sp_spaceused 'PRODUTO'

SELECT *
FROM PRODUTO
WHERE ATIVO_PRODUTO = 1

