USE DB

SELECT *
FROM SYS.fulltext_languages

CREATE TABLE EXEMPLO_FULLTEXT
( 
	COD_EXEMPLO_FULLTEXT INT IDENTITY PRIMARY KEY,
	DADOS_EXEMPLO_FULLTEXT TEXT 
)

INSERT EXEMPLO_FULLTEXT 
VALUES ('ABC DO TRUCO'), 
	('BATATINHA QUANDO NASCE'), 
	('PLANTAÇÃO DE BATATA SEM MESTRE'), 
	('TRUCO SEM MESTRE')

SELECT * 
FROM EXEMPLO_FULLTEXT
WHERE DADOS_EXEMPLO_FULLTEXT = 'XXX'

SELECT * 
FROM EXEMPLO_FULLTEXT
WHERE DADOS_EXEMPLO_FULLTEXT LIKE '%MESTRE%'

CREATE FULLTEXT CATALOG DB
WITH ACCENT_SENSITIVITY = ON
AS DEFAULT

SELECT DB_NAME()

EXEC SP_FULLTEXT_DATABASE ENABLE

EXEC sp_help EXEMPLO_FULLTEXT

EXEC SP_FULLTEXT_TABLE EXEMPLO_FULLTEXT, 
	'CREATE', 
	'DB', 
	'PK__EXEMPLO___CFDC277C4F2F915E' 

EXEC SP_FULLTEXT_COLUMN EXEMPLO_FULLTEXT,
	'DADOS_EXEMPLO_FULLTEXT',
	'ADD', 
	'BRAZILIAN'

EXEC SP_FULLTEXT_TABLE EXEMPLO_FULLTEXT,
	'ACTIVATE'

ALTER FULLTEXT INDEX ON EXEMPLO_FULLTEXT
SET CHANGE_TRACKING = AUTO

--CRIAR AGENDAMENTO PARA CADA 5 MINUTOS

SELECT *
FROM EXEMPLO_FULLTEXT
WHERE CONTAINS(DADOS_EXEMPLO_FULLTEXT, 'TRUCO')

SELECT *
FROM EXEMPLO_FULLTEXT
WHERE CONTAINS(DADOS_EXEMPLO_FULLTEXT, 'BATATA AND NOT MESTRE OR TRUCO AND NOT MESTRE')

SELECT *
FROM EXEMPLO_FULLTEXT
WHERE CONTAINS(DADOS_EXEMPLO_FULLTEXT, 'NEAR((TRUCO, MESTRE), 2, TRUE)')

SELECT *
FROM EXEMPLO_FULLTEXT
WHERE FREETEXT(DADOS_EXEMPLO_FULLTEXT, 'BATATA')

SELECT *
FROM SYS.fulltext_system_stopwords
WHERE language_id = 1046

--agnaldo@50minutos.com.br



